# Generated by Django 4.2.4 on 2023-10-12 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(
                    max_length=500, verbose_name='Description')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), (
                    'CONTRIBUTOR', 'Contributor')], default='CONTRIBUTOR', max_length=11, verbose_name='Role')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('TASK', 'Task'), (
                    'FEATURE', 'Feature')], max_length=10, verbose_name='Issue Tag')),
                ('status', models.CharField(choices=[('TODO', 'ToDo'), ('INPROGRESS', 'In Progress'), (
                    'FINISHED', 'Finished')], default='TODO', max_length=11, verbose_name='Issue Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), (
                    'HIGH', 'High')], max_length=10, verbose_name='Issue Priority')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(
                    max_length=500, verbose_name='Description')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BACK-END', 'Back-End'), ('FRONT-END', 'Front-End'),
                 ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10, verbose_name='Project Type')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(
                    max_length=500, verbose_name='Description')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
    ]
